### ISSUE TITLE
Remove apply's try-catch or improve error message

### ISSUE THREAD

**Issue by sebastianseilund** [faceyspacey/extract-css-chunks-webpack-plugin#117]
This block in `src/index.js`:

```js
    try {
      const isHOT = this.options.hot ? true : isHMR(compiler);

      if (isHOT && compiler.options.module && compiler.options.module.rules) {
        compiler.options.module.rules = this.updateWebpackConfig(compiler.options.module.rules);
      }
    } catch (e) {
      throw new Error(`Something went wrong: contact the author: ${JSON.stringify(e)}`);
    }
```

Makes it very difficult to track down errors in webpack builds. I first saw this error before identifying the issue in #116. All I saw was:

```
Something went wrong: contact the author: {}
```

`JSON.stringify`'ing `Error` objects gives you an empty JSON object.

1. Why the try-catch? Wrapping an error in "something went wrong - contact the author" doesn't add any extra information.
2. If you would like to keep the try-catch, I think we should improve the error message to include e.g. `e.stack || e` or something in the new error's message. And maybe also write who the author is or what project the error is from, since users may see this without knowing they're using extract-css-chunks-webpack-plugin (e.g. through react-static).

I'd be happy to submit a fix using either (1) or (2) above, but wanted your opinion first. Thanks!

**Comment by ScriptedAlchemy** [comment]
If you can / would like to improve the error handling, I’ll gladly accept a PR

Ideally 2, providing info to the user

**Comment by ScriptedAlchemy** [comment]
Bumping this. I’m not the best at error handling

**Comment by ScriptedAlchemy** [comment]
@sebastianseilund

**Comment by sebastianseilund** [comment]
Whoa, sorry for no+slow reply here.

Thinking about this once more, I'd definitely recommend that you just remove the try-catch and leave the body of the try clause.

If the code fails due to a bug in this module, then wrapping it in an extra `Something went wrong` error does not provide any value.

If the code fails due to invalid input by the user (e.g. bad webpack config), you should rather add validation here in the module and throw a specific error. E.g. `Value of x has to be y...`.

Are there any specific requirements on the user's input? Or was the try-catch block just added because you're not confident that it doesn't have a bug in it?

**Comment by ScriptedAlchemy** [comment]
hey man dont worry about it, ive got alot of projects and 15 day replies are not even noticed, i just do the rounds and bump things here and there. 

The users input, no not really, its more because of so many webpack config possibilities, i dont know exactly what will fail. So the error thow is so they contact me and i can patch another missed config style. 

I havent revieved one in like 8 months, so ill remove the try catch, ill also open a pr and comment here to get your feedback. We are very open to input and our users are the only thing that keeps us popular.

Ill open a PR tonight seeing as its so simple to fix
