### ISSUE TITLE
HMR only reloads entry css instead of chunks

### ISSUE THREAD

**Issue by clarkdo** [faceyspacey/extract-css-chunks-webpack-plugin#132]
My current app includes an entry (app.js) and async chunk (about.js) which all have their own css file, and `hotLoader.js` and `hotModuleReplacement.js` will be bundled into `app.js` or `vendors(if splitChunks enabled)`.

For example: 

1. In initialization of `getCurrentScriptUrl`, since `hotModuleReplacement.js` is in `app.js` or `vendor`, so the `document.currentScript.src` value is `http://localhost:3000/_nuxt/app.js` which should be `"http://localhost:3000/_nuxt/about.js`, then all the `src` corresponding to `module` are `app.js`

![image](https://user-images.githubusercontent.com/4312154/49645645-a6d3fa00-fa14-11e8-84dd-10e046ccf3eb.png)

2. When HMR reloading for `about.js` gets triggered, every reloading will only serve `app.css` instead of correct `about.js`.

For quick fix, I'm using `reloadAll` to reload all css files, but this way may by not the correct and efficient way to solve it, so I hope it can be solved in a better way, I'd highly appreciate any help!

**Comment by Nettsentrisk** [comment]
It seems as long as you are creating a common chunk (like vendors), document.currentScript.src is always the script including the runtime/bootstrap, so then every stylesheet is being classified as part of the common chunk bundle, instead of its actual bundle. So the common chunk is always being reloaded, instead of the correct bundle.

reloadAll "works", but only because you're reloading every single CSS bundle currently loaded on the page... It should be picking up and reloading the correct bundle file that the changed file belongs to :)

**Comment by ScriptedAlchemy** [comment]
If anyone has some ideas on how i can fix this, I’d loooooove to.

Reload all is a best effort to bring. HMR to css, i think we are the only plugin that exists which can hot reload css in webpack 4. Which makes it harder to draw inspiration from other authors

**Comment by ScriptedAlchemy** [comment]
Ran new release, let me know if this is any better
