### ISSUE TITLE
Do you have typescript definition file provided for version 4.x?

### ISSUE THREAD

**Issue by fwh1990** [faceyspacey/extract-css-chunks-webpack-plugin#153]
I install this package from npm, and `.d.ts` file is missing. It seems like you have merged ts file last year.

**Comment by ScriptedAlchemy** [comment]
This is actually a copy over of my work to mini-css-extract (pull request open) because I’ve moved to working with webpack, it made sense to align projects. I don’t know typescript so I’m not able to write the definitions for this new rebuild. If anyone knows how, I’ll endure their work also gets into mini-css
