### ISSUE TITLE
Does not correctly respect chunk names for JS but does for CSS.

### ISSUE THREAD

**Issue by swernerx** [faceyspacey/extract-css-chunks-webpack-plugin#17]
I use a custom Webpack plugin which assigns unique names to async bundles based on the filename of the original request. This normally works fine, but does not seem to do so in conjunction with this plugin.

This is my current output of the build folder:

```
0.ChYuiNiA.js
0.ChYuiNiA.js.map
0.ChYuiNiA.no_css.js
0.ChYuiNiA.no_css.js.map
1.PCG5c39I.js
1.PCG5c39I.js.map
1.PCG5c39I.no_css.js
1.PCG5c39I.no_css.js.map
2.x2b3QoW0.js
2.x2b3QoW0.js.map
2.x2b3QoW0.no_css.js
2.x2b3QoW0.no_css.js.map
Example-UiOo.2ZYWo4LK.css
Example-UiOo.2ZYWo4LK.css.map
Home-c5Cz.2oqLxilO.css
Home-c5Cz.2oqLxilO.css.map
Missing-hCnx.3QfDEPz1.css
Missing-hCnx.3QfDEPz1.css.map
bootstrap-kkgquqTl.js
bootstrap-kkgquqTl.js.map
bootstrap-kkgquqTl.no_css.js
bootstrap-kkgquqTl.no_css.js.map
file-169UXchv.woff
file-1KKLU3wg.woff
file-3ENWh3H7.woff
file-4GZ3FUwx.woff
file-4agheuvj.woff
file-4syhECVn.woff
file-6RC4peRz.svg
index.html
main.2nwstuSC.css
main.2nwstuSC.css.map
main.OXnPgBCq.js
main.OXnPgBCq.js.map
main.OXnPgBCq.no_css.js
main.OXnPgBCq.no_css.js.map
stats.json
```

Instead of the "names": 0, 1, 2 I would expect the names as we see them in the corresponding CSS files e.g. Missing, Example and Home.

It seems we always have CSS files named using the Bundle ID instead of the name.

**Comment by faceyspacey** [comment]
Unless it is this very plugin--I noticed the same issue with Webpack's magic comments. Basically `stats.assetsByChunkName` has the correct keys (i.e. the assigned chunk names). But then the files are missing them. 

Perhaps this plugin breaks that, but my feeling is it's an issue with Webpack itself. I'll know soon, as I'm releasing a new faster version of this plugin that doesn't have the `no_css.js` files. Instead I provide a babel-plugin which transforms `import()` into `Promise.all([import(), fetchCss()])`. 

That will make this plugin a lot faster and require less of the custom things I do. So if that doesn't solve the problem, it's likely a Webpack thing. To find out, all we have to do is use magic comments without this plugin. If that's the case, we should create an Issue in the Webpack repo.

**Comment by swernerx** [comment]
Ooops, was still editing... you are fast. Damn ;) Thanks for the quick response. I'll check that.

**Comment by swernerx** [comment]
Sorry, was the missing `chunkFilename` in my new config. Still trying to port stuff over to your tech set-up.

**Comment by faceyspacey** [comment]
Are you using [RFR](https://github.com/faceyspacey/redux-first-router)?

...By the way I have something very slick coming out soon: `Universal.render(<App />)`. If you're using React Universal Component it will still work, but u'll get to delete the additional resolution options (I am gonna go the babel plugin route after all). But more importantly--and what is the true purpose of `react-universal-component`--you can now do the [async-reactor](https://github.com/xtuc/async-reactor/) stuff and more. That means universal data-fetching + multiple imports in a "stateless async component." On the server, any data you fetched, will be stringified for you to embed in the page, and will automatically be picked up on the client. `Universal.render()` does a 2 phase recursive promise-resolution approach (like Apollo) on both the client and server to marshal the data from the server to client and rehydrate your components. It will also have automatic/configurable pre-fetching built into Redux-First Router so you don't have to worry about that aspect.

Anyway, just wanted to let you know--because the ultimate setup here is a few days away. Again, it won't change what ur doing much. It won't add much. Rather, it will delete some things.

**Comment by swernerx** [comment]
I'm not yet using the Redux-First-Router - but that thingy is definitely interesting.

I have used different strategies over time. My current "battlefield" is this: https://github.com/sebastian-software/edge-boilerplate - It will be hopefully the base for the new project at my current customer.

**Comment by swernerx** [comment]
That's what I use for naming of chunks: https://github.com/sebastian-software/edge-boilerplate/blob/master/webpack/plugins/ChunkNames.js

**Comment by faceyspacey** [comment]
I see you're using redux + react-router :). 

I'll definitely help u out if u wanna give RFR a try. I got a big SSR + Code Splitting demo coming out today. DX for all this stuff is finally what I want it to be *at least*.

**Comment by faceyspacey** [comment]
You saw the magic comments article right:

https://medium.com/@faceyspacey/how-to-use-webpacks-new-magic-comment-feature-with-react-universal-component-ssr-a38fd3e296a

Why not just use magic comments?

**Comment by swernerx** [comment]
I don't like magic comments ;) I like this working automatically. These comments are just a hack to offer something the official import() API doesn't support.

**Comment by swernerx** [comment]
In this project there is no redux-router yet integrated... it's basically just code from somewhere else.

**Comment by swernerx** [comment]
The ChunkNames plugin does what I'd like it to do without any additional work on the app developer side.

**Comment by faceyspacey** [comment]
Still it's what Webpack is going with.

You may wanna check out this again:

https://astexplorer.net/#/gist/eac41ded27729129569ac6d1d475af1b/latest

It's the babel plugin I was talking about.

Besides creating the double import (js + css), it creates an ID from the imported file name or a magic comment `webpackChunkName` if available.

It could easily do the reverse and generate a magic comment based on the file name.

Then you have named chunks without having to name it. It doesn't do all you do to create the name. It's just the filename, which is a problem if u have the same file in multiple folders. But that could be solved obviously.

This package by the way will soon give you stringified css files by chunk name which you can embed in the served page, so that the double import can retrieve them via the `fetchCss` function you'll see in the babel plugin output.
