### ISSUE TITLE
(node:28150) DeprecationWarning: Chunk.modules is deprecated. Use Chunk.getNumberOfModules/mapModules/forEachModule/containsModule instead.

### ISSUE THREAD

**Issue by cescoferraro** [faceyspacey/extract-css-chunks-webpack-plugin#19]
i think webpack 3 renamed this https://github.com/faceyspacey/extract-css-chunks-webpack-plugin/blob/a9b036a74b0ab24c127ff2c3116e9483f83bf985/index.js#L58
Maybe thats why I getting this warning

**Comment by thomashuston** [comment]
+1 on this, I saw the same error when I upgraded to webpack 3

**Comment by faceyspacey** [comment]
the challenge is being compatible with 2.0. 

Also since at some point (hopefully soon) Webpack will support this stuff natively, this stuff won't be needed anymore:

https://medium.com/faceyspacey/webpacks-import-will-soon-fetch-js-css-here-s-how-you-do-it-today-4eb5b4929852

Unless someone wants to do some sorta check to see if the method is available i likely wont be able to get to this since it's just a warning.
