### ISSUE TITLE
Outdated dependencies.

### ISSUE THREAD

**Issue by swernerx** [faceyspacey/extract-css-chunks-webpack-plugin#28]
There is quite a range of dependencies in this package which are out-of-date. Unfortunately updating them is not very straightforward as it breaks more tests.

Biggest changes might be going from Webpack 2.2.0 to 3.4.1 and AJV from 4.11.2 to 5.2.2.

Updating right now I receive a lot of schema validation issues in AJV - probably some changes applied with the v5 major release. 

Updating Webpack itself looks safe.

BTW: There are currently 5 mocha tests failing in master (for me).

**Comment by faceyspacey** [comment]
Yea, the tests are for features that don't exist anymore (as this package is only for multiple dynamic chunks). What really needs to happen is I write tests for the stuff I made. 

But honestly since webpack will be getting first class support for this stuff I'm less inclined to spend the time.

Also, the original extract-text-webpack-plugin has a PR bringing it up to speed with 3.0, which hasn't been merged yet. When it has, what I would be most inclined to do is convince those guys to merge these features, then i'll work on the tests, etc, and just pass it all off to them.

However, they never wanted HMR in that package, as it's mainly for production builds. So my guess is a lot of this is just never gonna happen, and be a waste of time. I don't mind the warnings--cuz i know what they're about. There's only one warning right now about `dep.modules`. It shouldn't be a deterrent. And updating the deps won't work unless we make this in the 3.0 style. That's the primary thing.

So a middle option is once the ETWP gets merged to brought up to the 3.0 style. Maybe I'll just go grab that code and re-make this, even if they never pull this stuff in. That PR has taken a while because it's not priority since, again, the master plan is all this stuff built into webpack itself. 

It works. That's enough given this is a "stop-gap" solution. I'm going to close this, as i don't want people scared to use this solution when the most important thing right now is people start doing true universal code-split apps.
