### ISSUE TITLE
Move to webpack-contrib

### ISSUE THREAD

**Issue by michael-ciniawsky** [faceyspacey/extract-css-chunks-webpack-plugin#3]
@faceyspacey 👋  

I would like to discuss, how we can keep the ExtractTextPlugin and ExtractTextHMRPlugin (this repo) 😛  in sync in the future, could you wait with a release at least a few days ?

Besides the HMR implementation there are a few interesting chnages you made to ExtractTextPlugin, especially [this](https://github.com/faceyspacey/extract-css-chunks-webpack-plugin/blob/master/index.js#L314-L325) which would be a good PR on it's own :D

**Comment by faceyspacey** [comment]
If what you were saying is a request to stay in sink with ETWP. It shouldn't be a problem. Certainly I'd love help, and I'll actively merge. And of course I'll be on the look out too. If what you're asking is whether I'll be active and on top of it, the answer is yes.

If what you're talking is about merging this back up stream, I'm down to do whatever is best for the community. I think when the maintainers of ETWP see this it might change some of the "regulations" they've imposed on how they want HMR done (they want it built as a plugin of a plugin). Basically this repo should be their repo. So it all depends on them. @cletusw handled HMR. I handled code splitting. And we both already went though red-tape to get these changes merged into ETWP. Basically if that's to happen--and since we have put so much work in to no avail--it should be because the community motivates the ETWP maintainers to make it happen and they (or someone) invests time into it, which they don't seem to have much of. Then I'll play whatever role is necessary to do it. Right now, for me personally, my focus isn't a battle to get something merged. The reason is because it's a complex package and it will take a lot of work. The original maintainers really need to be ready to invest time. Simple as that. But I'm down to help with whatever they need.

**Comment by michael-ciniawsky** [comment]
I promise to come back to here soon 😛 I'm doing general maintance @webpack-contrib atm and therefore I'm not as deep into ETWP as you or @cletusw, we are always looking for maintainers to say it upfront. We need to find a good way to handle the situation here, but Tobias (sokra) basically rejected to have HMR in ExtractTextPlugin 'by default', besides that from a first glance, there are a  few good changes you  && || @cletusw made in addition to HMR and the HMR strory just needs to find it's acceptable place (but no idea where atm tbh :))

**Comment by faceyspacey** [comment]
i think we're on the same page. a turn of events make change @sokra 's opinion about things in our neck of the woods. 

Let's get people using this package, confirm it doesn't have extraneous problems and eventually merge it back in as webpack leadership gets serious about wanting its capabilities.

simple as that.

**Comment by michael-ciniawsky** [comment]
I need to do some other stuff during the day, but I will try this out and try to get sokra on the line later today/tommorrow and as soon as I now why && what I callback here 😛

**Comment by faceyspacey** [comment]
```
git clone https://github.com/faceyspacey/flush-chunks-boilerplate.git
cd flush-chunks-boilerplate
yarn
yarn start
```

The real movement starts here:

https://github.com/thejameskyle/react-loadable/pull/37

I look forward to hear what you think about `react-loadable` and `webpack-flush-chunks`. Next.js--even though it uses webpack--has given the status quo a run for its money. My view is advanced developers doing serious projects have no need to confine themselves to the limitations of a framework. But we need to get up to speed in code splitting. Until now code splitting has been more hype than reality (because of the missing pieces). There's a no reality upon us, and core tools need to catch up.

**Comment by faceyspacey** [comment]
Promise.resolve(

https://medium.com/@faceyspacey/code-cracked-for-code-splitting-ssr-in-reactlandia-react-loadable-webpack-flush-chunks-and-1a6b0112a8b8

).then(

https://github.com/webpack/webpack/issues/4993#issuecomment-307119627
perhaps sokra has more interest now that the code-splitting + SSR story is over. Particularly thanks to magic comments. This stuff is all first-class now; CSS in this environment with flawless DE is a must.

)

**Comment by faceyspacey** [comment]
@michael-ciniawsky hey brother, `hashedModuleIdsPlugin` doesn't seem to be working with what I've done on this plugin (at least in one place):

https://github.com/faceyspacey/extract-css-chunks-webpack-plugin/blob/master/loader.js#L126

so for example I need to be getting things:

```js
webpackJsonp([0], {
  "0eCr": function (e, a, t) {
    e.exports = {
      paragraph: "Example__paragraph--1_Go3"
    }
  },
```

but I'm getting this:

```js
webpackJsonp([0], {
  "0eCr": function (e, a, l) {
    e.exports = {
      paragraph: "Example__paragraph--1_Go3"
    },
    l("fjbf")([
      [
        '/Users/jamesgillmore/React/flush-chunks-boilerplate-webpack-chunkNames/node_modu' +
            'les/css-loader/index.js?{"modules":true,"localIdentName":"[name]__[local]--[hash' +
            ':base64:5]"}!/Users/jamesgillmore/React/flush-chunks-boilerplate-webpack-chunkNa' +
            'mes/src/css/Example.css',
        ".Example__paragraph--1_Go3{color:purple;font-size:32px}"
      ]
    ], "")
  },
```

The line that generates that string is this one:

https://github.com/faceyspacey/extract-css-chunks-webpack-plugin/blob/master/loader.js#L139

I assume it's because what I've injected can't be stripped out (I'm at the wrong compilation phase). Any tips?

**Comment by faceyspacey** [comment]
This is to solve this issue by the way:

https://github.com/faceyspacey/flush-chunks-boilerplate-webpack-chunknames/issues/1
