### ISSUE TITLE
not able to get raw css

### ISSUE THREAD

**Issue by rahulkumar26** [faceyspacey/extract-css-chunks-webpack-plugin#49]
webpack.config.js

`{
      test: /\.css$/,
      exclude: path.join(__dirname, '../../src/styles'),
      use: ExtractCssChunks.extract({
        use: [
          'raw-loader',
        ]
      })
    }`

`new ExtractCssChunks({ filename: 'sass/async/[name].css' }),`

I was trying to extract the raw css file, but in all chunks getting similar CSS content. However, when using the style-loader it works fine but not raw.

Any help would be appreciated!

**Comment by faceyspacey** [comment]
Honestly, I know nothing about raw-loader. If it's not working with it, while working otherwise, it likely just doesn't work unfortunately.

Also, it's not even supposed to be used with `style-loader`. It's supposed to be used with `css-loader` directly as you see here:

https://github.com/faceyspacey/universal-demo/blob/master/webpack/client.dev.js#L31

style-loader creates stylesheets and puts them in the head via javascript. Here, we just want to get the css, and let this plugin create new stylesheet files. 

One option may be to use `raw-loader` in conjunction with `css-loader`, similar to what I did here with the `stylus-loader`:

https://github.com/faceyspacey/universal-demo/blob/master/webpack/client.dev.js#L31

So perhaps by chaining the 2 loaders you can get the desired result.
