### ISSUE TITLE
HMR Not working on latest

### ISSUE THREAD

**Issue by dmitrif** [faceyspacey/extract-css-chunks-webpack-plugin#98]
Hi!

I yet again have yet to create a trimmed down example of the problem, but for now this is the issue.
We have HMR enabled (using the `hot`) parameter, however not seeing the hot-loader code being injected into any bundles. Therefore when an update is made, the style include is never reloaded.

What am I possibly missing?

Thanks.

**Comment by dmitrif** [comment]
Seems like the plugin has the following lines:
        ```if (isHOT && compiler.options.module && compiler.options.module.rules) {
          const updatedRules = compiler.options.module.rules.reduce((rules, rule) => {
            if (rule.use && Array.isArray(rule.use)) {```

However, when a console log is added, our `compiler.options.module.rules` looks like:
```rules: [ { parser: [Object] }, { oneOf: [Array] } ]```

**Comment by ScriptedAlchemy** [comment]
Hey, i see the issue here. Any chance you could make a small demo repo with your webpack config. or can you send me a stder output of your webpack JSON object. 

Ill fix this but want to make sure i can see whats going on


**Alternatively** can you open a PR, seeing as you know the exact lines in my code that cause it to stop. IF you PR a working version, ill merge it! Otherwise ill need some more info from you

**Comment by dmitrif** [comment]
Damn, that's what I get for not checking github more often. Had a PR ready but seeing as you fixed it, thank you! <3

**Comment by dmitrif** [comment]
Although... I may still submit the PR since oneOf / use can be nested indefinitely from my understanding.

**Comment by ScriptedAlchemy** [comment]
Dude, if you can clean that up a bit --- ill totally accept the PR, thank you for working on it and i am sorry to have waisted your time. 

Will gladly accept improvements to the plugin

**Comment by dmitrif** [comment]
https://github.com/faceyspacey/extract-css-chunks-webpack-plugin/pull/103 PR created :)
